---
apiVersion: v1
kind: Pod
metadata:
  name: house-music
  namespace: jenkins
  labels:
    name: house-music
    jenkins-project: house-music
spec:
  securityContext:
    runAsUser: 0
  containers:
    - name: java
      image: openjdk:8-alpine
      command:
        - cat
      tty: true
    - name: node
      image: node:alpine
      command:
        - cat
      tty: true
    - name: docker-build
      image: docker:dind
      tty: true
      securityContext:
        privileged: true
